
name: Lint & Tests

on:
  push:
    branches: [main]
    paths:
      - 'app/**'
      - 'requirements.txt'
      - 'requirements.dev.txt'

jobs:
  lint-test:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test 
        run: docker-compose run --rm api sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker-compose run --rm api sh -c "flake8"